### ISSUE TITLE
Unexpected crash of the app

### ISSUE THREAD

**Issue by pegas511** [ibnc/mountebankMongo#1]
I tried it on mb versions: 2.6.0 and 2.8.2
I created dabase in mongo and tried to post a new imposter, received error below
`[mb:2525] error creating imposter: {"message":"stubs.loadRequests is not a function","name":"TypeError","stack":"TypeError: stubs.loadRequests is not a function\n    at loadRequests (/opt/homebrew/lib/node_modules/mountebank/src/models/imposter.js:196:51)\n    at addRequestsTo (/opt/homebrew/lib/node_modules/mountebank/src/models/imposterPrinter.js:58:35)\n    at Object.toJSON (/opt/homebrew/lib/node_modules/mountebank/src/models/imposterPrinter.js:98:19)\n    at Object.toJSON (/opt/homebrew/lib/node_modules/mountebank/src/models/imposter.js:200:49)\n    at post (/opt/homebrew/lib/node_modules/mountebank/src/controllers/impostersController.js:130:45)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"} `

if I go to localhost:2525/imposters it crashes
```
info: [http:4557 MexicoBackground] Open for business...
error: [mb:2525] error creating imposter: {"message":"stubs.loadRequests is not a function","name":"TypeError","stack":"TypeError: stubs.loadRequests is not a function\n    at loadRequests (/opt/homebrew/lib/node_modules/mountebank/src/models/imposter.js:196:51)\n    at addRequestsTo (/opt/homebrew/lib/node_modules/mountebank/src/models/imposterPrinter.js:58:35)\n    at Object.toJSON (/opt/homebrew/lib/node_modules/mountebank/src/models/imposterPrinter.js:98:19)\n    at Object.toJSON (/opt/homebrew/lib/node_modules/mountebank/src/models/imposter.js:200:49)\n    at post (/opt/homebrew/lib/node_modules/mountebank/src/controllers/impostersController.js:130:45)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
info: [mb:2525] GET /images/book.jpg
/opt/homebrew/lib/node_modules/mountebank/src/controllers/impostersController.js:89
            promises = allImposters.map(imposter => imposter.toJSON(queryOptions));
                                                             ^

TypeError: imposter.toJSON is not a function
    at /opt/homebrew/lib/node_modules/mountebank/src/controllers/impostersController.js:89:62
    at Array.map (<anonymous>)
    at getAllJSON (/opt/homebrew/lib/node_modules/mountebank/src/controllers/impostersController.js:89:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async get (/opt/homebrew/lib/node_modules/mountebank/src/controllers/impostersController.js:106:29)

Node.js v20.0.0
```
But all imposters were saved to a database and I can observe it
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/55977385/235116205-bb942775-c4ef-4f23-9369-875112f1dce1.png">

**Comment by joaopedroft** [comment]
I have a similar problem with getting imposters it gives `imposter.toJSON is not a function` and on posting it gives `server.stubs.toJSON is not a function`.

I am using node 16.16

**Comment by btull89** [comment]
I too am seeing a `server.stubs.toJSON is not a function` error

**Comment by tamilsm** [comment]
If anyone is still looking for a fix: 

`imposter.toJSON is not a function` issue is caused by losing the mountebank object references when serializing and storing the functions in MongoDB. 

`server.stubs.toJSON is not a function` issue is because the `stubsFor` function is asynchronous while mountebank expects this to be synchronous. 

I've fixed both these issues in my PR: #4
